config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :movies, only: [:show] do
    resources :reviews, except: [:index] do
      resources :votes, only: [:new, :create, :update]
      resources :comments, only: [:new, :create, :edit, :update] do

      end
      end
    resources :comments, only: [:new, :create, :edit, :update] do
      resources :comments, only: [:new, :create, :edit, :update]
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :edit, :update] do
    resources :comments, only: [:new, :create, :edit, :update]
  end

  resources :genres, only: [:index, :show]

  resources :reviews, except: [:index] do
    resources :comments, only: [:new, :create, :edit, :update]
  end
  # resources :votes, only: [:new, :create, :update]
  root to: 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user, only: [:new, :create, :edit, :update]

  def new
    @post = Comment.find_by_id(params[:comment_id])
    @review = Review.find_by_id(params[:review_id])
    @movie = Movie.find_by_id(params[:movie_id])
    if @post
      @comment = @post.comments.new
    elsif @review
      @comment = @review.comments.new
    elsif @movie
      @comment = @movie.comments.new
    end
  end

  def create
    @movie = Movie.find_by_id(params[:movie_id])
    @post = Comment.find_by_id(params[:comment_id])
    @review = Review.find_by_id(params[:review_id])
    if @post
      @comment = @post.comments.create(comment_params)
      @comment.update(user_id: current_user.id)
    elsif @review
      @comment = @review.comments.create(comment_params)
      @comment.update(user_id: current_user.id)
      # redirect_to review_path(@review)
    elsif @movie
      @comment = @movie.comments.create(comment_params)
      @comment.update(user_id: current_user.id)
      # redirect_to movie_path(@movie.id)
    end
    # redirect somewhere else
    redirect_to determine_return_route
    # need to do conditional for failing comments
  end

  def edit
  end

  def update
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def determine_return_route
    # if @review
    #   return review_path(@review)
    if @movie
      return movie_path(@movie)
    else
      return root_path
    end
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment_body"><%=comment.body%></p>
  <h6>by: <%=link_to "#{comment.user.name}", user_path(comment.user)%> | <%= link_to "reply",  new_comment_path(movie_id: @movie, review_id: @review, comment_id: comment.id) %></h6>
  <div class="nested_comments">
    <%= render comment.comments %>
  </div>
</div>
<!-- new_polymorphic_path([comment.commentable, comment]) -->
<!-- [@movie, @review, comment], action: "new" -->

app/views/comments/_form.html.erb
<table>
  <%= form_for [movie, review, post, comment] do |f| %>
    <tr>
      <td><%= f.label "Comment" %></td>
      <td><%= f.text_area :body %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit %></td>
    </tr>
  <% end %>
</table>

app/views/comments/new.html.erb
<h2>Add a comment</h2>

<div>
  <p>You are replying to:</p>
  <% if @post %>
    <%= @post.body %>
    <%= render partial: "form", locals: {movie: @movie, review: @review, post: @post, comment: @comment} %>
   <% elsif @review %>
    <%= @review.body %>
    <%= render partial: "form", locals: {movie: @movie, review: @review, post: nil, comment: @comment} %>
  <% elsif @movie %>
    <%= @movie.title %>
    <%= render partial: "form", locals: {movie: @movie, review: nil, post: nil, comment: @comment} %>
  <% end %>
</div>