config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :movies, only: [:show] do
    resources :reviews, except: [:index] do
      resources :votes, only: [:new, :create, :update]
      resources :comments, only: [:new, :create, :edit, :update] do

      end
      end
    resources :comments, only: [:new, :create, :edit, :update] do
      resources :comments, only: [:new, :create, :edit, :update]
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :edit, :update] do
    resources :comments, only: [:new, :create, :edit, :update]
  end

  resources :genres, only: [:index, :show]

  resources :reviews, except: [:index] do
    resources :comments, only: [:new, :create, :edit, :update]
  end
  # resources :votes, only: [:new, :create, :update]
  root to: 'welcome#index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    @movie = Movie.find_by(id: params[:id])
    @vote = Vote.new
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :runtime, :synopsis, :genre)
  end
end

app/views/movies/_movie.html.erb
<!-- THIS IS THE MOVIE STUB PARTIAL -->

<li class="movie-stub">
  <div><%=movie.aggregate_score%>% <a href="<%=movie_path(movie)%>"><%= movie.title %></a></div>
</li>

app/views/movies/show.html.erb
<div id="movie_details">
  <h1><%=@movie.title %></h1>
  <p>Runtime: <%=@movie.runtime%> | Aggregate Score: <%=@movie.aggregate_score %></p>

  <p>Genre:
    <%= link_to(@movie.genre.name, genre_path(@movie.genre)) %>
  </p>
  <h3>Synopsis: </h3>
  <p><%=@movie.synopsis%></p>
</div>
<h3>Discuss this Movie: </h3>
<p><%= link_to "New Comment",  new_comment_path(movie_id: @movie, review_id: @review) %></p>
<div id="discussion">
  <%=render @movie.comments%>
</div>
<h3>Reviews: </h3>
<p><%= link_to "New Review",  new_review_path(movie_id: @movie) %></p>
<div id="review_stubs">
  <%=render @movie.reviews%>
</div>