config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :movies, only: [:show] do
    resources :reviews, except: [:index] do
      resources :votes, only: [:new, :create, :update]
      resources :comments, only: [:new, :create, :edit, :update] do

      end
      end
    resources :comments, only: [:new, :create, :edit, :update] do
      resources :comments, only: [:new, :create, :edit, :update]
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :edit, :update] do
    resources :comments, only: [:new, :create, :edit, :update]
  end

  resources :genres, only: [:index, :show]

  resources :reviews, except: [:index] do
    resources :comments, only: [:new, :create, :edit, :update]
  end
  # resources :votes, only: [:new, :create, :update]
  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Database</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%# javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= csrf_meta_tags %>

</head>
<body>

<div class="container">
  <div class="page-header">
    <ul class="nav nav-pills pull-right">
      <% if logged_in? %>
      <li>
        <%= button_to('Log Out', session_path, method: :delete) %>
      </li>
      <% else %>
      <li>
        <%= link_to("Sign Up", new_user_path) %>
      </li>
      <li>
        <%= link_to("Log In", new_session_path) %>
      </li>
      <% end %>
    </ul>
    <h1><%= link_to("The Best Movie Database", root_path) %></h1>
  </div>
</div>
<div class="container" id="main-content">
  <%= yield %>
</div>
</body>
</html>